apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-service-config
  namespace: togglemaster
data:
  PORT: "8005"
  AWS_REGION: "us-east-2"
  AWS_SQS_URL: "https://sqs.us-east-2.amazonaws.com/986263532741/toggle-master-evaluation-events"
  AWS_DYNAMODB_TABLE: "ToggleMasterAnalytics"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: togglemaster
  labels:
    app: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: 986263532741.dkr.ecr.us-east-2.amazonaws.com/analytics-service:e2a0b6405e53f2bfe46557dd09fcf4f3f69d43a8
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8005
          envFrom:
            - configMapRef:
                name: analytics-service-config
          readinessProbe:
            httpGet:
              path: /health
              port: 8005
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8005
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: togglemaster
spec:
  selector:
    app: analytics-service
  ports:
    - port: 8005
      targetPort: 8005
