apiVersion: v1
kind: ConfigMap
metadata:
  name: evaluation-service-config
  namespace: togglemaster
data:
  PORT: "8004"
  AWS_REGION: "us-east-2"
  AWS_SQS_URL: "https://sqs.us-east-2.amazonaws.com/986263532741/toggle-master-evaluation-events"
  FLAG_SERVICE_URL: "http://flag-service:8002"
  TARGETING_SERVICE_URL: "http://targeting-service:8003"
  REDIS_URL: "redis://togglemaster-redis.sgmrw5.0001.use2.cache.amazonaws.com:6379"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: evaluation-service
  namespace: togglemaster
  labels:
    app: evaluation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evaluation-service
  template:
    metadata:
      labels:
        app: evaluation-service
    spec:
      containers:
        - name: evaluation-service
          image: 986263532741.dkr.ecr.us-east-2.amazonaws.com/evaluation-service:dc4654967fd1e6c04f36feedee06216bc10932d2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8004
          envFrom:
            - configMapRef:
                name: evaluation-service-config
            - secretRef:
                name: evaluation-service-secrets
          readinessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: evaluation-service
  namespace: togglemaster
spec:
  selector:
    app: evaluation-service
  ports:
    - port: 8004
      targetPort: 8004
