name: evaluation-service CI
on:
  push:
    branches: [main]
    paths:
      - "evaluation-service/**"
      - ".github/workflows/evaluation-service.yml"
      - ".github/workflows/_service-ci.yml"
  pull_request:
    paths:
      - "evaluation-service/**"
jobs:
  ci:
    permissions:
      contents: write
    uses: ./.github/workflows/_service-ci.yml
    with:
      service_name: evaluation-service
      language: go
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
