name: flag-service CI

on:
  push:
    branches: [main]
    paths:
      - "flag-service/**"
      - ".github/workflows/flag-service.yml"
      - ".github/workflows/_service-ci.yml"
  pull_request:
    paths:
      - "flag-service/**"

jobs:
  ci:
    uses: ./.github/workflows/_service-ci.yml
    with:
      service_name: flag-service
      language: python
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
